### ISSUE TITLE
General TODO

### ISSUE THREAD

**Issue by chamelopi** [chamelopi/fls-helper#1]
- [ ] Possibility to enter path and directly jump there (if existing)
- [ ] Prevent editing of table entries, but allow selection
- [ ] Selecting a table cell always selects the entire row
- [ ] Allow extracting of multiple files (-> multi-selection), but permit other actions for more than one file at a time
